version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: "poetry run python -m kube_hound ${ARGS}"
  
  kubesec:
    image: kubesec/kubesec:v2
    ports:
      - 8080:8080
    command: ["http", "8080"]
    environment:
      - TYPE=static,dynamic
      - ANALISYS=kubesec