repositories:
  main:
    git: https://github.com/GoogleCloudPlatform/microservices-demo.git

deployment:
  kubernetes:
    repository: main
    glob: kubernetes-manifests/*.yaml

services:
  - name: emailservice
    image: emailservice
    repository: main
    dockerfile: src/emailservice/Dockerfile
    sourcecode: src

  - name: productcatalogservice
    image: productcatalogservice
    repository: main
    dockerfile: src/productcatalogservice/Dockerfile
    sourcecode: src

  - name: recommendationservice
    image: recommendationservice
    repository: main
    dockerfile: src/recommendationservice/Dockerfile
    sourcecode: src

  - name: shippingservice
    image: shippingservice
    repository: main
    dockerfile: src/shippingservice/Dockerfile
    sourcecode: src

  - name: checkoutservice
    image: checkoutservice
    repository: main
    dockerfile: src/checkoutservice/Dockerfile
    sourcecode: src

  - name: paymentservice
    image: paymentservice
    repository: main
    dockerfile: src/paymentservice/Dockerfile
    sourcecode: src

  - name: currencyservice
    image: currencyservice
    repository: main
    dockerfile: src/currencyservice/Dockerfile
    sourcecode: src

  - name: cartservice
    image: cartservice
    repository: main
    dockerfile: src/cartservice/src/Dockerfile
    sourcecode: src

  - name: frontend
    image: frontend
    repository: main
    dockerfile: src/frontend/Dockerfile
    sourcecode: src

  - name: frontend-external
    repository: main
    sourcecode: src

  - name: adservice
    image: adservice
    repository: main
    dockerfile: src/adservice/Dockerfile
    sourcecode: src

properties:
  frontend-external:
    external: true
